apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tekton-default-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: authors-tekton
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""