apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: authors-pipeline
spec:
  resources:
  - name: source-repo
    type: git
  - name: builtImage
    type: image
  params:
  - name: imageTag
    type: string
    description: Image Tag Version
    default: GA
  - name: pathToDockerFile
    type: string
    description: Kaniko - docker file location
    default: ./frontend/Dockerfile
  - name: pathToContext
    type: string
    description: kaniko - workspace path
    default: /workspace/workspace/
  tasks:
  - name: init-grab-build-push
    taskRef:
      name: build-push-authors
    params:
    - name: imageTag
      value: "$(params.imageTag)"
    - name: pathToDockerFile
      value: "$(params.pathToDockerFile)"
    - name: pathToContext
      value: "$(params.pathToContext)"
    resources:
      inputs:
      - name: workspace
        resource: source-repo
      outputs:
      - name: builtImage
        resource: builtImage
     
  - name: proceed-deploy-smoke-green
    runAfter: [init-grab-build-push]
    taskRef:
         name: deploy-smoke-green
    resources:
      inputs:
      - name: builtImage
        resource: builtImage
    params:
      - name: imageTag
        value: "$(params.imageTag)"
         