apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ws-default-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: workshop
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
