apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: jenkins-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: hl-jenkins
  namespace: workshop
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
