apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-smoke-green
spec:
  inputs:
    resources:
    - name: builtImage
      type: image
    params:
    - name: imageTag
      description: Image tagging
      default: latest
  steps:
  - name: patch-green
    image: lachlanevenson/k8s-kubectl:v1.17.3
    command: ["kubectl"]
    args:
    - "patch" 
    - "deployment" 
    - "authors-green" 
    - "-p {\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"workshop\",\"image\":\"$(inputs.resources.builtImage.url):$(inputs.params.imageTag)\"}]}}}}"
  - name: start-green-pod 
    image: lachlanevenson/k8s-kubectl:v1.17.3
    command: ["kubectl"]
    args:
    - "scale" 
    - "--replicas=1" 
    - "deployment"
    - "authors-green" 
  - name: wait-for-green-ready
    image: lachlanevenson/k8s-kubectl:v1.17.3
    command: ["kubectl"]
    args:
    - "wait" 
    - "--for=condition=ready" 
    - "pod"
    - "-l app=authors-green" 
    - "--timeout=60s"